### PR TITLE
Add some sleeps on node start up and join to avoid failure

### PR DESCRIPTION
**Pull request by hazen**
Without these sleeps my VM would constantly fail

### CODE REVIEW

**Comment by lukebakken** [comment]
- What OS?
- What were the failures?

**Comment by hazen** [comment]
The OS is either CentOS 6.7 or CentOS 7.1

```
2016-01-17 00:19:22 [info]: Removing old Riak data
2016-01-17 00:19:22 [info]: Configuring riak.conf
2016-01-17 00:19:22 [info]: Starting Riak
Join failed. Try again in a few moments.
Exiting!
```

**Comment by lukebakken** [comment]
Thanks, I'll give it a try on my CentOS VM.

**Comment by lukebakken** [comment]
works-on-my-machine-badge

I even turned down my CentOS 7 VM to one processor and 1GiB ram to slow it down.

I'll make this an option or env var instead.

**Comment by lukebakken** [comment]
Added feature as the `-d SECS` option.

**Comment by lukebakken** [comment]
@javajolt - interesting - I just ran into this when starting up a Riak TS cluster. It has never happened with plain Riak. Do you think it could mean an issue?

**Comment by hazen** [comment]
Not sure.  Don't know why it would be any slower than regular Riak to start up.  I could bring it up in standup today.

**Comment by lukebakken** [comment]
Were you using Riak TS as well?

**Comment by hazen** [comment]
No.  For the NodeJS PR I was using 2.1.3 IIRC

**Comment by lukebakken** [comment]
OK who knows what's up then.

**Pull request merged**
